#!/usr/bin/env bash
# Embed arbitrary binary files (CLI tools, archives, anything) into
# self-extracting shell scripts, and restore them back. Generalization of
# embed-tgz.sh: no file-type restriction, and the executable bit of the
# source file is recorded and restored.
#
# embed:    for every <file> given, generate <file>.sh next to it (or into
#           --output-dir). The generated file is a standalone POSIX shell
#           script carrying the payload as base64 with its sha256; nothing
#           from this repo is needed to restore it.
# restore:  two equivalent ways to get the binary back:
#             a) run the generated script directly:   ./sops-v3.13.2.linux.amd64.sh
#             b) via this tool:                       embed-cli.sh extract sops-v3.13.2.linux.amd64.sh
#           Both write the original-named file into the current directory (or
#           -o target), verify the sha256, restore the exec bit if the source
#           had one, and refuse to overwrite unless --force is given
#           (FORCE=1 env for the generated script).
#
# Usage:
#   embed-cli.sh embed   [-d OUTDIR] [-f] file1 [file2 ...]
#   embed-cli.sh extract [-o OUTFILE|-d OUTDIR] [-f] embedded.sh [...]
#
# Options:
#   -d, --output-dir DIR   write generated/restored files into DIR
#   -o, --output FILE      extract only: explicit output path (single input)
#   -f, --force            overwrite existing output files
#   -h, --help             this help
set -euo pipefail

usage() { sed -n '2,28p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

# macOS base64 decodes with -D on older releases, -d on Linux/newer macOS.
if printf 'QQ==' | base64 -d >/dev/null 2>&1; then B64D="-d"; else B64D="-D"; fi

sha256_of() {
  if command -v sha256sum >/dev/null; then sha256sum "$1" | cut -d' ' -f1
  else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

[ $# -ge 1 ] || usage 1
MODE="$1"; shift
case "$MODE" in embed|extract) ;; -h|--help) usage ;; *)
  echo "error: mode must be 'embed' or 'extract', got '$MODE'" >&2; usage 1 ;;
esac

OUTDIR=""
OUTFILE=""
FORCE=0
ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    -d|--output-dir) OUTDIR="$2"; shift 2 ;;
    -o|--output)     OUTFILE="$2"; shift 2 ;;
    -f|--force)      FORCE=1; shift ;;
    -h|--help)       usage ;;
    -*)              echo "unknown option: $1" >&2; usage 1 ;;
    *)               ARGS+=("$1"); shift ;;
  esac
done
[ ${#ARGS[@]} -gt 0 ] || { echo "error: no input files given" >&2; usage 1; }
[ -z "$OUTFILE" ] || [ ${#ARGS[@]} -eq 1 ] || {
  echo "error: -o only valid with a single input file" >&2; exit 1; }
[ -z "$OUTDIR" ] || mkdir -p "$OUTDIR"

refuse_existing() {  # $1 = path
  if [ -e "$1" ] && [ "$FORCE" -eq 0 ]; then
    echo "error: '$1' exists (use --force to overwrite)" >&2
    return 1
  fi
}

# --- embed -------------------------------------------------------------------
do_embed() {  # $1 = source file path
  local src="$1" base out sha exec_bit
  [ -f "$src" ] || { echo "error: '$src' not found" >&2; return 1; }
  base=$(basename "$src")
  case "$base" in *.sh)
    echo "error: '$src' already ends in .sh — refusing to double-embed" >&2
    return 1 ;;
  esac
  out="${OUTDIR:-$(dirname "$src")}/${base}.sh"
  refuse_existing "$out" || return 1
  sha=$(sha256_of "$src")
  exec_bit=0; [ -x "$src" ] && exec_bit=1

  {
    printf '#!/bin/sh\n'
    printf '# Self-extracting archive generated by embed-cli.sh — running this\n'
    printf '# script restores the embedded file into the current directory\n'
    printf '# (or $1 if given), verifies its sha256, and restores the exec bit.\n'
    printf 'NAME="%s"\n' "$base"
    printf 'SHA256="%s"\n' "$sha"
    printf 'EXEC="%s"\n' "$exec_bit"
    cat <<'RESTORE'
set -eu
OUT="${1:-$NAME}"
if [ -e "$OUT" ] && [ "${FORCE:-0}" != "1" ]; then
  echo "error: '$OUT' exists (re-run with FORCE=1 to overwrite)" >&2; exit 1
fi
if printf 'QQ==' | base64 -d >/dev/null 2>&1; then B64D="-d"; else B64D="-D"; fi
# payload = everything after the marker line
sed -n '/^__PAYLOAD_BELOW__$/,$p' "$0" | sed '1d' | base64 $B64D > "$OUT"
if command -v sha256sum >/dev/null; then GOT=$(sha256sum "$OUT" | cut -d' ' -f1)
else GOT=$(shasum -a 256 "$OUT" | cut -d' ' -f1); fi
if [ "$GOT" != "$SHA256" ]; then
  echo "error: checksum mismatch for '$OUT' (corrupt payload)" >&2
  rm -f "$OUT"; exit 1
fi
[ "$EXEC" = "1" ] && chmod +x "$OUT"
echo "restored $OUT ($SHA256)"
exit 0
__PAYLOAD_BELOW__
RESTORE
    base64 < "$src"
  } > "$out"
  chmod +x "$out"
  echo "embedded $src -> $out"
}

# --- extract -----------------------------------------------------------------
do_extract() {  # $1 = embedded .sh path
  local sh="$1" name sha exec_bit out got
  [ -f "$sh" ] || { echo "error: '$sh' not found" >&2; return 1; }
  name=$(sed -n 's/^NAME="\(.*\)"$/\1/p' "$sh" | head -1)
  sha=$(sed -n 's/^SHA256="\([0-9a-f]\{64\}\)"$/\1/p' "$sh" | head -1)
  exec_bit=$(sed -n 's/^EXEC="\([01]\)"$/\1/p' "$sh" | head -1)
  if [ -z "$name" ] || [ -z "$sha" ] || \
     ! grep -q '^__PAYLOAD_BELOW__$' "$sh"; then
    echo "error: '$sh' was not generated by embed-cli.sh (header/marker missing)" >&2
    return 1
  fi
  out="${OUTFILE:-${OUTDIR:-.}/$name}"
  refuse_existing "$out" || return 1
  sed -n '/^__PAYLOAD_BELOW__$/,$p' "$sh" | sed '1d' | base64 $B64D > "$out"
  got=$(sha256_of "$out")
  if [ "$got" != "$sha" ]; then
    echo "error: checksum mismatch for '$out' (corrupt payload)" >&2
    rm -f "$out"; return 1
  fi
  [ "$exec_bit" = "1" ] && chmod +x "$out"
  echo "extracted $sh -> $out ($got)"
}

FAILED=0
for f in "${ARGS[@]}"; do
  if [ "$MODE" = "embed" ]; then do_embed "$f" || FAILED=1
  else do_extract "$f" || FAILED=1; fi
done
exit "$FAILED"
