#!/usr/bin/env bash
# Embed .tgz files into self-extracting shell scripts, and restore them back.
#
# embed:    for every <chart>.tgz given, generate <chart>.tgz.sh next to it (or
#           into --output-dir). The generated file is a standalone POSIX shell
#           script carrying the tgz as base64 with its sha256; nothing from this
#           repo is needed to restore it.
# restore:  two equivalent ways to get the binary .tgz back:
#             a) run the generated script directly:   ./mychart-1.2.3.tgz.sh
#             b) via this tool:                       embed-tgz.sh extract mychart-1.2.3.tgz.sh
#           Both write the original-named .tgz into the current directory (or
#           -o target), verify the sha256, and refuse to overwrite unless
#           --force is given (FORCE=1 env for the generated script).
#
# Usage:
#   embed-tgz.sh embed   [-d OUTDIR] [-f] chart1.tgz [chart2.tgz ...]
#   embed-tgz.sh extract [-o OUTFILE|-d OUTDIR] [-f] embedded.tgz.sh [...]
#
# Options:
#   -d, --output-dir DIR   write generated/restored files into DIR
#   -o, --output FILE      extract only: explicit output path (single input)
#   -f, --force            overwrite existing output files
#   -h, --help             this help
set -euo pipefail

usage() { sed -n '2,24p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

# macOS base64 decodes with -D on older releases, -d on Linux/newer macOS.
if printf 'QQ==' | base64 -d >/dev/null 2>&1; then B64D="-d"; else B64D="-D"; fi

sha256_of() {
  if command -v sha256sum >/dev/null; then sha256sum "$1" | cut -d' ' -f1
  else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

[ $# -ge 1 ] || usage 1
MODE="$1"; shift
case "$MODE" in embed|extract) ;; -h|--help) usage ;; *)
  echo "error: mode must be 'embed' or 'extract', got '$MODE'" >&2; usage 1 ;;
esac

OUTDIR=""
OUTFILE=""
FORCE=0
ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    -d|--output-dir) OUTDIR="$2"; shift 2 ;;
    -o|--output)     OUTFILE="$2"; shift 2 ;;
    -f|--force)      FORCE=1; shift ;;
    -h|--help)       usage ;;
    -*)              echo "unknown option: $1" >&2; usage 1 ;;
    *)               ARGS+=("$1"); shift ;;
  esac
done
[ ${#ARGS[@]} -gt 0 ] || { echo "error: no input files given" >&2; usage 1; }
[ -z "$OUTFILE" ] || [ ${#ARGS[@]} -eq 1 ] || {
  echo "error: -o only valid with a single input file" >&2; exit 1; }
[ -z "$OUTDIR" ] || mkdir -p "$OUTDIR"

refuse_existing() {  # $1 = path
  if [ -e "$1" ] && [ "$FORCE" -eq 0 ]; then
    echo "error: '$1' exists (use --force to overwrite)" >&2
    return 1
  fi
}

# --- embed -------------------------------------------------------------------
do_embed() {  # $1 = tgz path
  local tgz="$1" base out sha
  [ -f "$tgz" ] || { echo "error: '$tgz' not found" >&2; return 1; }
  case "$tgz" in *.tgz) ;; *)
    echo "error: '$tgz' is not a .tgz file" >&2; return 1 ;;
  esac
  base=$(basename "$tgz")
  out="${OUTDIR:-$(dirname "$tgz")}/${base}.sh"
  refuse_existing "$out" || return 1
  sha=$(sha256_of "$tgz")

  {
    printf '#!/bin/sh\n'
    printf '# Self-extracting archive generated by embed-tgz.sh — running this\n'
    printf '# script restores the embedded file into the current directory\n'
    printf '# (or $1 if given), then verifies its sha256.\n'
    printf 'NAME="%s"\n' "$base"
    printf 'SHA256="%s"\n' "$sha"
    cat <<'RESTORE'
set -eu
OUT="${1:-$NAME}"
if [ -e "$OUT" ] && [ "${FORCE:-0}" != "1" ]; then
  echo "error: '$OUT' exists (re-run with FORCE=1 to overwrite)" >&2; exit 1
fi
if printf 'QQ==' | base64 -d >/dev/null 2>&1; then B64D="-d"; else B64D="-D"; fi
# payload = everything after the marker line
sed -n '/^__PAYLOAD_BELOW__$/,$p' "$0" | sed '1d' | base64 $B64D > "$OUT"
if command -v sha256sum >/dev/null; then GOT=$(sha256sum "$OUT" | cut -d' ' -f1)
else GOT=$(shasum -a 256 "$OUT" | cut -d' ' -f1); fi
if [ "$GOT" != "$SHA256" ]; then
  echo "error: checksum mismatch for '$OUT' (corrupt payload)" >&2
  rm -f "$OUT"; exit 1
fi
echo "restored $OUT ($SHA256)"
exit 0
__PAYLOAD_BELOW__
RESTORE
    base64 < "$tgz"
  } > "$out"
  chmod +x "$out"
  echo "embedded $tgz -> $out"
}

# --- extract -----------------------------------------------------------------
do_extract() {  # $1 = embedded .sh path
  local sh="$1" name sha out got
  [ -f "$sh" ] || { echo "error: '$sh' not found" >&2; return 1; }
  name=$(sed -n 's/^NAME="\(.*\)"$/\1/p' "$sh" | head -1)
  sha=$(sed -n 's/^SHA256="\([0-9a-f]\{64\}\)"$/\1/p' "$sh" | head -1)
  if [ -z "$name" ] || [ -z "$sha" ] || \
     ! grep -q '^__PAYLOAD_BELOW__$' "$sh"; then
    echo "error: '$sh' was not generated by embed-tgz.sh (header/marker missing)" >&2
    return 1
  fi
  out="${OUTFILE:-${OUTDIR:-.}/$name}"
  refuse_existing "$out" || return 1
  sed -n '/^__PAYLOAD_BELOW__$/,$p' "$sh" | sed '1d' | base64 $B64D > "$out"
  got=$(sha256_of "$out")
  if [ "$got" != "$sha" ]; then
    echo "error: checksum mismatch for '$out' (corrupt payload)" >&2
    rm -f "$out"; return 1
  fi
  echo "extracted $sh -> $out ($got)"
}

FAILED=0
for f in "${ARGS[@]}"; do
  if [ "$MODE" = "embed" ]; then do_embed "$f" || FAILED=1
  else do_extract "$f" || FAILED=1; fi
done
exit "$FAILED"
